spring:
  datasource:
    username: dbuser
    password: '{cipher}AQBGgyxfyvPO4kMVyeurAJlXzspAg9rNHx80HoOWHZUEfwC0LwAjGYF2OsBYJRVtmuIa5t/fkT+gCyeNWQBlWY8snKhUSwdFkH0iCqtViC6TBzKPFUa/0gGaRAq9k+6oh2mGpMQQIt+CXDqBNTz1jS4bI2tzkmJ69eD6Oc3jdqjPLsTCIJx+o93QU9rsf7SpS0Tp/vM4lPLMk3i58tKrnFo1z8FNCfrtC36vnmN6cViak+1BdUH4vjVfLVL2a3VAsWbl/lrVyGTZBYhXEpdJdDkz6EwSMKdIihB9dlL2iXlxBOGzfByqxySE6AlKYsxa0tphNB5XiuNi98Woz7mKKcQ/HAHscnbSDXp3BPwQFwpOvgYgrXo0cU/YMsxSPHCOiqk='
